# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Week7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week7
	pod 'Alamofire', '~> 5.4'
	pod 'Toast-Swift', '~> 5.0.1'
	pod 'IQKeyboardManagerSwift'

end
